version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ar-namecard-api
    restart: unless-stopped
    # .env.docker 파일에 정의된 포트 변수를 사용합니다.
    ports:
      - "${API_HTTP_PORT:-3000}:3000"
      - "${API_HTTPS_PORT:-3443}:3443"
    # .env.docker 파일로부터 모든 환경 변수를 로드합니다.
    env_file:
      - .env.docker
